CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    total_value NUMERIC(19,2) NOT NULL CHECK (total_value > 0),
    created_at TIMESTAMPTZ NOT NULL
);
