ALTER TABLE orders ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE orders ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN last_error VARCHAR(1000);
ALTER TABLE orders ADD COLUMN updated_at TIMESTAMPTZ;
UPDATE orders SET updated_at = created_at;
ALTER TABLE orders ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE orders ADD CONSTRAINT ck_orders_status CHECK (status IN ('PENDING','PROCESSING','SUCCESS','ERROR'));
